spring:
  application:
    name: scorpio-paas-sync
switch:
  update: false
aries:
  datasource:
    url: jdbc:mysql://localhost:3306/scorpio-paas-hxl?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
hxl:
  datasource:
    url: jdbc:mysql://localhost:3306/scorpio-honest?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver